# Generated by Django 3.0.5 on 2020-04-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polling_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pu_date',
            new_name='pub_date',
        ),
    ]
